name: duckdb-spawn
services:
  - name: api
    type: container
    instance_type: nano
    regions:
      - fra
    ports:
      - port: 8000
        protocol: http
    env:
      - key: DATABASE_URL
        value: /data/duckdb_spawn.db
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: LOG_LEVEL
        value: info
      - key: ENVIRONMENT
        value: staging
    container:
      image: ${DOCKER_HUB_USERNAME}/duckdb-spawn:${GITHUB_SHA}
      registry: docker
    scaling:
      min_instances: 1
      max_instances: 1
    routes:
      - path: /
        port: 8000
    healthcheck:
      port: 8000
      path: /monitoring/health
      initial_delay: 30s