name: duckdb-spawn
services:
  - name: api
    type: docker
    docker:
      image: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
    ports:
      - name: http
        port: 8000
    env:
      - name: DATABASE_URL
        value: /data/duckdb_spawn.db
    resources:
      cpu: 500m
      memory: 512Mi
    regions:
      - fra
