name: duckdb-spawn
services:
  - name: api
    instance_type: nano
    regions: ["fra"]
    ports:
      - port: 8000
        protocol: http
    env:
      - name: DATABASE_URL
        value: /data/duckdb_spawn.db
      - name: PYTHONUNBUFFERED
        value: "1"
      - name: LOG_LEVEL
        value: info
      - name: ENVIRONMENT
        value: staging
    resources:
      memory: 512Mi
      cpu: 0.1 