global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'duckdb-spawn'
    static_configs:
      - targets: ['duckdb-spawn-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 4s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']