name: duckdb-spawn
runtime: python
description: DuckDB Data Product deployment configuration
config:
  duckdb-spawn:
    apiPort: integer
    prometheusPort: integer
    environment: string
    logLevel: string
    imageTag: string
    koyeb_token:
      type: string
      secret: true
  registry:
    username: string
    password:
      type: string
      secret: true