global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'

scrape_configs:
  - job_name: 'duckdb-spawn'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['duckdb-spawn-api:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'data-product-api'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'go_.*'
        action: drop
    scrape_interval: 5s
    scrape_timeout: 4s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'prometheus_tsdb_.*'
        action: keep

# Add basic auth if needed
# basic_auth:
#   username: admin
#   password: ${PROMETHEUS_PASSWORD}