name: Deploy to Staging

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Ensure this matches your local environment

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Install Pulumi
      uses: pulumi/actions@v3
      with:
        command: version

    - name: Pulumi Login
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      run: pulumi login

    - name: Pulumi Stack Select
      run: pulumi stack select staging

    - name: Pulumi Up
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      run: pulumi up --yes
