name: Deploy to Koyeb

on:
  push:
    branches:
      - main

env:
  KOYEB_APP_NAME: duckdb-spawn
  KOYEB_SERVICE_NAME: api

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Koyeb CLI
        run: |
          curl -sSL https://get.koyeb.com | bash
          echo 'Adding Koyeb CLI to PATH'
          echo 'export PATH="$HOME/.koyeb/bin:$PATH"' >> $GITHUB_ENV

      # Step 3: Authenticate with Koyeb
      - name: Authenticate with Koyeb
        env:
          KOYEB_API_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
        run: |
          source $GITHUB_ENV
          koyeb login --api-token $KOYEB_API_TOKEN

      # Step 4: Deploy to Koyeb
      - name: Deploy to Koyeb
        env:
          KOYEB_API_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
        run: |
          source $GITHUB_ENV
          koyeb apps list