name: Deploy to Koyeb

on:
  push:
    branches:
      - main  # Or your staging branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install the Koyeb CLI
      - name: Install Koyeb CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh | sh
          echo "$HOME/.koyeb/bin" >> $GITHUB_PATH

      # Step 3: Verify Koyeb CLI Installation
      - name: Verify Koyeb CLI Installation
        run: |
          koyeb --version
          ls -l $HOME/.koyeb/bin

      # Step 4: Authenticate with Koyeb
      - name: Authenticate with Koyeb
        env:
          KOYEB_API_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
        run: |
          koyeb login --api-token $KOYEB_API_TOKEN

      # Step 5: Deploy to Koyeb
      - name: Deploy to Koyeb
        env:
          KOYEB_API_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
        run: koyeb apps list