name: Deploy to Koyeb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install and configure Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_API_TOKEN }}"

      - name: Build and deploy to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: duckdb-spawn
          service-name: api
          service-env: "PYTHONUNBUFFERED=1,LOG_LEVEL=info,ENVIRONMENT=staging"
          service-ports: "8000:http"
          service-routes: "/:8000"
          service-instance-type: "nano"
          service-regions: "fra"
          service-checks: "8000:http:/monitoring/health"
          git-branch: main
          git-builder: docker
          