name: Deploy to Koyeb

on:
  push:
    branches:
      - main

env:
  KOYEB_APP_NAME: duckdb-spawn
  KOYEB_SERVICE_NAME: api

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Koyeb CLI
        run: |
          curl -sSL https://get.koyeb.com | bash
          echo 'Adding Koyeb CLI to PATH'
          echo "$HOME/.koyeb/bin" >> $GITHUB_PATH

      - name: Verify Koyeb CLI Installation
        run: koyeb --version

      - name: Authenticate with Koyeb
        env:
          KOYEB_API_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
        run: koyeb login --api-token $KOYEB_API_TOKEN

      - name: Deploy to Koyeb
        env:
          KOYEB_API_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
        run: koyeb apps list